### PR TITLE
Fix category labels on preview

### LINKED ISSUE #1: Goal Assesment in DocToolXR not showing up in export
Basic information

Title

Provide a clear and concise title that summarizes the issue for effective ticket handling.
Goal Assesment in DocToolXR not showing up in export

Description

Start by briefly outlining the problem. Clearly state your expectations and describe the actual outcome. Be specific and avoid unnecessary details.
I can add the goals and also rate the goals but the rating will not show up on the export page.

Steps to Reproduce

Clearly outline the steps that lead to the bug. Provide a step-by-step guide for developers to reproduce the problem, including any relevant settings or configurations.

Clearly state your expected result (at each step) and contrast it with the actual result. This may not be necessary for routine steps (e.g., filling in the title field of a content type-unless there's something wrong with that, of course), but include it when there's a problem. This approach helps developers quickly identify deviations from expected behavior.

Example

Create a Question Set (1.20.12) content with a True False (1.8.x) question.
Disable the “Retry” option either in the behavioral settings of the Question Set or in the behavioral settings of the True False question.
Save the content.
Start the Question Set, navigate to the True False question and hit the “Check” button without selecting “true” or “false” as the answer option of the True False question.

Result: One is stuck and cannot finish the Question Set, because the “Finish” button does not pop up.

Expected behavior: The “Finish” button appears in order to finish the Question Set.
Open Doctool, produce a goal page and a goal assessment page and then creat goals, go to export page. does not show up
Environment Details

H5P Content Type Name (or part of H5P)

It's important to use the correct English name. To avoid misunderstandings, cross-reference the original English content type name at https://h5p.org/content-types-and-applications.
DocumentationToolXR

Browser

Please state the browser name (e,g, Chrome, Firefox or Safari) and also state the version number unless it's a problem on the server-side only. There typically is a menu/settings item named "Help" or "About" that will reveal the version number to you.
Lumi

H5P Integration

Please specify what H5P integration you are using. If you have administrative access, please also determine the version number.
Lumi
Supplements

Link to screenshot or screen recording (1)
https://d.pr/i/1uYZc8

Link to screenshot or screen recording (2)

Link to screenshot or screen recording (3)

Link to page where content is hosted online or link to H5P content file.
Additional Information

Additional Information

Include any additional details that might be relevant to understanding the bug. This could include the

date and time the issue was discovered,
recent changes to the server or platform or H5P integration or content type,
other plugins that might interfere with H5P,
…

### PR DESCRIPTION
**Pull request by otacke**
Fixes https://github.com/codefluegel/h5p-document-export-page-xr/issues/1

### CODE REVIEW

File: src/scripts/create-document.js [hunk 1]
```diff
@@ -224,10 +224,10 @@ H5P.DocumentExportPageXR.CreateDocument = (function ($, EventDispatcher) {
 
     this.exportableGoalsList.forEach(function (page) {
       if (page.label !== undefined && page.label.length) {
-        output.append('<p>', {
+        output.append($('<p>', {
```
Comment (patrickfrohmann) [inline src/scripts/create-document.js:227]: 👍
